apiVersion: apps/v1
kind: Deployment
metadata:
  name: cshimegi-blog-user
  namespace: cshimegi-blog-local
  labels:
    app: blog-user-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-user-deploy
  template:
    metadata:
      labels:
        app: blog-user-deploy
    spec:
      initContainers:
      - name: wait-for-db-before-startup
        image: busybox
        command:  ["sh", "-c", "until nc -z blog-db-service 3306 > /dev/null; do echo Waiting for master; sleep 2; done;"]
      containers:
      - name: blog-user-deploy
        image: cshimegi/blog-users:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
        envFrom:
        - configMapRef:
            name: blog-config
