apiVersion: v1
kind: Service
metadata:
  name: blog-db-service
  namespace: cshimegi-blog-local
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: blog-db-deploy
